- name: "/topological_navigation/feedback"
#  signal_when : 'not published'
  signal_lambdas:
  - "lambda msg: msg.feedback.route == 'WayPoint1'"
  execute:
  - action:
      user_msg: "Navigating to charging node."
      namespace: "/topological_navigation"
      package: "topological_navigation"
      action_prefix: "GotoNode"
      goal_args:
      -  "goal.target = 'WayPoint58'"
  lock_exec: False             # lock out other threads while this one is executing its sequence of actions
  timeout: 0.0                 
