- name : "/sim_amcl_error"
  map:
    topic_arg: "msg.y"
    limits: [-2.0, 21.0, -8.0, 8.0]
    resolution: 1.0
  include: True


- name : "/row_detector/health_monitor"
  map:
    topic_arg: "msg.lines_accepted.data"
    limits: [-2.0, 21.0, -8.0, 8.0]
    resolution: 1.0
  include: False
