- name : "/row_detector/health_monitor"
  signal_lambdas :
    - expression: "lambda msg : msg.data.lines_accepted == False"
      safety_critical: True
  execute:
  - call:
      service_name: "/base_driver/safety_stop"
      service_args:
      -  "req.data = True"
  timeout : 3.0
