on:
  push:
    branches:
      - release-test
    paths:
      - '*'
      - .github/workflows/release.yml
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  release:
    uses: SAGARobotics/SagaWorkflows/.github/workflows/release.yml@v2.0
    secrets:
      pat-token: ${{ secrets.SERVICE_ACCOUNT_PAT_REPO_READ }}
      repo-user: ${{ secrets.SAGA_REPO_WRITE_USER }}
      repo-pass: ${{ secrets.SAGA_REPO_WRITE_PASS }}
    
